<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks68拍；.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

 /*
 * This zh-CN (Simplified used in mainland) translation is made by Austin Huang (im@austinhuang.me)
 * https://austinhuang.me
 * US/CA :  +1 (808) 468-0313 (Text/Voicemail only)
 * UK    : +44 (843) 558-5832 (Call/Voicemail only. Subject to 0843 calling fees)
 */
return [
    'Add New Server' => '添加新的服务器',
    'Add Your Server' => '添加新的服务器',
    'Add Bot' => '邀请机器人',
    'Add a Tag' => '添加标签',
    'Bad Request' => '请求无效',
    'Bump' => '顶',
    'Cancel' => '取消',
    'Categorize your server by keywords (e.g. game title)' => '您可以使用关键词（如游戏名称）。',
    'Category' => '分类',
    'Dashboard' => '设定',
    'Description' => '介绍',
    'Discord Servers Bumped Recently' => '最近顶过的服务器',
    'Don\'t forget to check "Set this link to never expire"' => '请确保服务器邀请无失效期！（服务器永久邀请码应为7字母长）',
    'Edit' => '編集',
    'Games' => '游戏',
    'If you don\'t add a bot, you can NOT present various informations about your server, create an invitation link or bump up your servers with commands' => '若不邀请机器人，您将无法在服务器页面显示各种信息（如服务器成员列表），创建邀请链接或使用命令来顶服务器。',
    'Invite Link' => '邀请链接',
    'Join this Server' => '加入该服务器',
    'Language' => '语言',
    'Login' => '登陆',
    'Logout' => '退出',
    'Main Language' => '主要语言',
    'Member Count' => '成员',
    'Not Found' => '找不到页面',
    'Please enter no more than {tagLimit} tags.' => '您最多只能添加{tagLimit}个标签。',
    'Please select a server' => '请选择服务器',
    'Please wait another {0, plural, =1{# minute} other{# minutes}} until the server can be bumped' => '请再等{0}分钟！',
    'Private' => '私密',
    'Public' => '公开',
    'Public Discord Servers' => 'Discord服务器列表',
    'Recommended' => '推荐',
    'Save' => '保存',
    'Search' => '搜索',
    'Select a Category' => '选择分类',
    'Select a Server' => '选择服务器',
    'Select a server to add to the public server list on DISBOARD' => '请选择添加到DISBOARD的服务器。',
    'Servers' => '服务器',
    'Tags' => '标签',
    'This server is private. Only the owner (you) can view it.' => '本服务器不在公共列表上。只有服主（您）可以看到它。',
    'This server is not public because invite URL is not set' => '由于未设置邀请链接，本服务器现在未显示在列表上。',
    'This will add this server to our public server list' => '选择该框以将服务器置于公共列表上',
    'Unspecified' => '未选择',
    'User' => '用户',
    'Users' => '用户',
    'You haven\'t added a server yet' => '您从未添加过服务器！',
    'Your servers' => '您的服务器',
    'Your server has been bumped' => '服务器已顶！',
    'Your server has been saved successfully' => '服务器信息已保存！',
    'just now' => '刚刚',
    '{0, plural, =1{# day} other{# days}} ago' => '{0}日前',
    '{0, plural, =1{# hour} other{# hours}} ago' => '{0}小时前',
    '{0, plural, =1{# minute} other{# minutes}} ago' => '{0}分钟前',
    '{0, plural, =1{# second} other{# seconds}} ago' => '{0}秒前',
    /* Welcome Messages on home page */
    'Public <span class="discord-logo">Discord</span> Servers' => 'Public <span class="discord-logo">Discord</span> Servers',
    '<strong class="brand">DISBOARD</strong> is the place where you can <strong>list/find Discord servers</strong>.' => '<strong class="brand">DISBOARD</strong>是一个让你 <strong>寻找及分享Discord服务器</strong>的地方。',
    'Find and join some awesome servers listed here.' => '加入那些有趣的服务器，',
    'Or <a href="{login-url}">login</a> and <strong>add your server if you are a server owner</strong> 😎' => '或者<a href="/login">登陆</a>并且 <strong>添加自己拥有的服务器</strong> 😎',
    'Add Your Server!' => '添加新的服务器!', // The large button
    /* Categories */
    'Adventure Games' => '冒险游戏',
    'All Games' => '游戏综合',
    'Anime and Manga' => '动漫',
    'Community' => '社区',
    'Computers' => '电脑',
    'FPS Games' => '第一人称射击（FPS）游戏',
    'MMO Games' => '多人在线（MMO）游戏',
    'MOBA Games' => '多人竞技（MOBA）游戏',
    'Movies' => '电影',
    'Music' => '音乐',
    'Other' => '其他',
    'Party Games' => '派对游戏',
    'Programming' => '编程',
    'Puzzle Games' => '拼图游戏',
    'RPG Games' => 'RPG',
    'Retro Games' => '怀旧游戏',
    'Sandbox Games' => '沙盒游戏',
    'Simulation Games' => '模拟游戏',
    'Sports Games' => '体育游戏',
    'Strategy Games' => '战略游戏',
    'TCG Games' => '卡片（TCG）游戏',
    'Tabletop Games' => '桌面游戏',
];
