<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks68拍；.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
 /*
 * This zh-CN (Simplified used in mainland) translation is made by Austin Huang (im@austinhuang.me)
 * https://austinhuang.me
 * US/CA :  +1 (808) 468-0313 (Text/Voicemail only)
 * UK    : +44 (843) 558-5832 (Call/Voicemail only. Subject to 0843 calling fees)
 */
return [
    'Ascending' => 'Aufsteigend',
    'Add New Server' => 'Füge einen neuen Server hinzu',
    'Add Your Server' => 'Füge deinen Server hinzu',
    'Add Bot' => 'Füge deinen Bot hinzu',
    'Add a Tag' => 'Füge einen Tag hinzu',
    'Add <b>CREATE_INSTANT_INVITE</b> and <b>SEND_MESSAGES</b> permissions to DISBOARD bot.' => 'Füge <b>Soforteinladungen erstellen</b> und <b>Nachrichten senden</b> Berrechtigungen zu dem DISBOARD Bot hinzu.',
    'Admin servers' => 'Administratoren Server',
    'After that send this command: <span class="tag is-light">!disboard refresh</span>' => 'Nachdem du den Command gesendet hast: <span class="tag is-light">!disboard refresh</span>',
    'Are you sure you want to delete {serverName}?' => 'Bist du dir sucher das du {serverName} löschen möchtest?',
    'Are you sure you want to delete this review?' => 'Bist du dir sicher das du diese Rezension löschen möchtest?',
    'Bad Request' => 'Falsche Anfrage',
    'Bump' => 'Bump',
    'Cancel' => 'Abbruch',
    'Categorize your server by keywords (e.g. game title)' => 'Kategorisiere deinen Server mit Schlüsselwörten (z.B. Spiel Titel)',
    'Category' => 'Kategorie',
    'Could not delete the server' => 'Fehler beim Löschen dieses Servers',
    'Could not delete the review' => 'Fehler beim löschen dieser Rezension',
    'Dashboard' => 'Dashboard',
    'Descending' => 'Absteigende Reihenfolge',
    'Description' => 'Beschreibung',
    'Delete server' => 'Server löschen',
    'Delete review' => 'Rezension löschen',
    'Discord Server List' => 'Discord Server Liste',
    'Discord Servers Bumped Recently' => 'Discord Server vor kurzem gebumpt',
    'Discord servers tagged with {tag}' => 'Liste der Discord Server mit dem Tag: {tag}',
    '<span class="discord-logo">Discord</span> Servers' => '<span class="discord-logo">Discord</span> Server',
    'Discord servers tagged with <strong>{tag}</strong>' => 'Discord Server mit dem Tag: <strong>{tag}</strong>',
    'Don\'t forget to check "Set this link to never expire"' => 'Vergessen nicht den Link auf "Setze diesen Link auf \'Niemals ablaufen\'" zu setzen',
    'Edit' => 'Bearbeiten',
    'Enter keyword(s)' => 'Gebe Keywords ein',
    'Failed to Sync' => 'Fehler beim syncronisieren',
    'Games' => 'Spiele',
    'Go to Dashboard' => 'Gehe zum Dashboard',
    'Go Home' => 'Gehe zur Startseite',
    'Home' => 'Startseite',
    'If you don\'t add a bot, you can NOT present various informations about your server, create an invitation link or bump up your servers with commands' => 'Wenn Sie keine Bots einladen, können Sie verschiedene Informationen auf der Serverseite (z. B. eine Liste von Servermitgliedern) nicht anzeigen, Einladungslinks erstellen oder Bump Commands verwenden',
    'If your server isn\'t in the above list or dropdown, sync with Discord manually' => 'Wenn Ihr Server nicht in der obigen Liste oder im Dropdown-Menü angezeigt wird, synchronisieren sie ihn bitte manuell mit Discord',
    'In DISBOARD, you can now write reviews and add ratings for servers you are joining.<br>Let\'s recommend your favorite servers to other people!' => 'Sie können nun Rezensionen für Server schreiben auf denen sie gejoint sind<br>Lass uns deinen Lieblinsserver weiterempfehlen!',
    'Invite Link' => 'Einladungslink',
    'Join this Server' => 'Trete diesem Server bei',
    'Language' => 'Spache',
    'Login' => 'Anmelden',
    'Logout' => 'Abmelden',
    'Main Language' => 'Haupt-Sprache',
    'Manage Server' => 'Server verwalten',
    'Member Count' => 'Benutzer-Zähler',
    '{time, plural, =1{# minute} other{# minutes}}' => '{time} Minuten',
    'New Review' => 'Neue Rezension',
    'Not Found' => 'Nicht gefunden',
    'No results found for <strong>{keyword}<strong>' => 'Für <strong>{keyword}</strong> wurde keine Ergebnisse gefunden',
    'Official Discord Server' => 'Offizieller Discord Server',
    'Owner servers' => 'Beseitzer Server',
    'Please enter no more than {tagLimit} tags.' => 'Bitte füge nicht mehr als {tagLimit} Tags hinzu',
    'Please select a server' => 'Bitte wähle einen Server aus',
    'Please wait another {0, plural, =1{# minute} other{# minutes}} until the server can be bumped' => 'Bitte warten noch einmal {0} Minuten！',
    'Popular Tags' => 'Oft genutzte Tags',
    'Private' => 'Privat',
    'Public' => 'Öffentlich',
    'Public Discord Servers' => 'Öffentliche Discord Server',
    'Public Discord Server List' => 'Öffentliche Discord Server Liste',
    'Rating' => 'Bewertung',
    'Read more' => 'Lese mehr',
    'Recommended' => 'Erweitert',
    'Review' => 'Rezension',
    'Reviews' => 'Rezensionen',
    'Review {serverName}' => 'Rezension {serverName}',
    'Save' => 'Spchern',
    'See: <a href="{url}" target="_blank">screen capture</a>' => 'Siehe <a href="{url}" target="_blank">Bildschirmfoto</a>',
    'See More Discord Servers' => 'Finde mehr Discord Server',
    'Search' => 'Suchen',
    'Search Discord Servers' => 'Suche Discord Server',
    'Search Options' => 'Such Einstellungen',
    'Select a Category' => 'Wähle eine Kategorie aus',
    'Select a Server' => 'Wähle einen Server aus',
    'Select a server to add to the public server list on DISBOARD' => 'Wähle einen Server aus um ihn zur öffentlichen Liste auf DISBOARD hinzuzufügen',
    'Servers' => 'Server',
    'Tags' => 'Tags',
    'This server is private. Only the owner (you) can view it.' => 'Dieser Server ist privat nur der Besitzer (du) kannst ihn sehen',
    'This server is not public because invite URL is not set' => 'Dieser Server ist noch nicht öffentlich weil der Einladungslink nicht nicht gesetzt wurde',
    'This will add this server to our public server list' => 'Dass wird deinen Server zut öffentlichsen Server Liste hinzufügen',
    'Unspecified' => 'Unspezifiert',
    'User' => 'Benutzer',
    'Users' => 'Benutzer',
    'You haven\'t added a server yet' => 'Du hast den Server noch nicht jetzt hinzugefügt!',
    'Your servers' => 'Deine Server',
    'Your server has been bumped' => 'Dein Server wurde gebumpt',
    'Your server has been saved successfully' => 'Dein Serber wurde erfolgreich hinzugefügt',
    'just now' => 'Jetzt',
    '{0, plural, =1{# day} other{# days}} ago' => '{0} Tage davor',
    '{0, plural, =1{# hour} other{# hours}} ago' => '{0} Stunden davor',
    '{0, plural, =1{# minute} other{# minutes}} ago' => '{0} Minuten davor',
    '{0, plural, =1{# second} other{# seconds}} ago' => '{0} Sekunden davor',
    /* Welcome Messages on home page */
    'Public <span class="discord-logo">Discord</span> Servers' => '<strong class="brand">DISBOARD</strong> ist der Ort wo du <strong>Discord Server listen/finden</strong> kannst.',
    '<strong class="brand">DISBOARD</strong> is the place where you can <strong>list/find Discord servers</strong>.' => '<<strong class="brand">DISBOARD</strong> ist der Ort wo du <strong>Discord Server listen/finden</strong> kannst.',
    'Find and join some awesome servers listed here.' => 'Finde und joine wundervollen Servern die hier gelistet sind',
    'Or <a href="{login-url}">login</a> and <strong>add your server if you are a server owner</strong> 😎' => 'Oder <a href="{login-url}">melde dich an</a> und <strong>füge deinen Server hinzu wenn du der Owner bist</strong> 😎',
    'Add Your Server!' => 'Füge deinen Server hinzu', // The large button
    /* Categories */
    'Adventure Games' => 'Abenteuer Spiele',
    'All Games' => 'Alle Spiele',
    'Anime and Manga' => 'Animie und Manga',
    'Community' => 'Gemeinschaften',
    'Computers' => 'Computer',
    'FPS Games' => 'FPS Spiele',
    'MMO Games' => 'MMO Spiele',
    'MOBA Games' => 'MOBA Spiele',
    'Movies' => 'Filme',
    'Music' => 'Musik',
    'Other' => 'Anderes',
    'Party Games' => 'Party Spiele',
    'Programming' => 'Programmieren',
    'Puzzle Games' => 'Puzzle Spiele',
    'RPG Games' => 'RPG Spiele',
    'Retro Games' => 'Alte Spiele',
    'Sandbox Games' => 'Sandbox Spiele',
    'Simulation Games' => 'Simulation\'s Spiele',
    'Sports Games' => 'Sport Spiele',
    'Strategy Games' => 'Strategie Spiele',
    'TCG Games' => 'TCG Spiele',
    'Tabletop Games' => 'Tichspiele',
];