<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Ascending' => 'تصاعدي',
    'Add New Server' => 'أضف سيرفر جديد',
    'Add Your Server' => 'أضف سيرفرك',
    'Add Bot' => 'أضف بوت',
    'Add a Tag' => 'أضف تاغ',
    'Add <b>CREATE_INSTANT_INVITE</b> and <b>SEND_MESSAGES</b> permissions to DISBOARD bot.' => 'إنشىء دعوة فورية <b>و</b> إرسال الرسائل</b> صلاحيات البوت',
    'Admin response' => 'رد الادمن',
    'Admin servers' => 'سيفرات الأدمن',
    'After that send this command: <span class="tag is-light">!d invite</span>' => 'من ثم إرسل هذا الأمر: <span class="tag is-light">!d invite</span>',
    'All Discord reviews' => 'جميع تقييمات الديسكورد',
    'All Discord servers' => 'جميع سيرفرات الديسكورد',
	'All shards are operational!' => 'جميع الشاردات تعمل!',
    'Are you sure you want to delete {serverName}?' => 'هل أنت متأكد بأنك تريد حذف {serverName}؟',
    'Are you sure you want to delete this review?' => 'هل أنت متأكد بأنّك تريد حذف هذا التقييم؟',
    'Bad Request' => 'طلب سيئ',
    'Be positive, constructive and respectful' => 'كن إيجابياً، محفزّاً وخلوقاً',
    'Bot Status' => 'حالة البوت',
    'Bump' => 'رفع',
    'Bumped At' => 'تم رفعه بـ',
    'Bumped {time}' => 'رُفع{time}',
    'Bumped recently' => 'رُفع مؤخراً',
    'Cancel' => 'إلغاء',
    'Categorize your server by keywords (e.g. game title)' => 'صنّف سيرفرك بكلمات مفتاحية مثل: اسم لعبة',
    'Category' => 'تصنيف',
    '<b>Categories</b> and <b>Popular tags</b>' =>  '<b>تاغات مشهورة</b> و <b>تصنيفات</b>',
    'Copied the URL' => 'تم نسخ الـرابط',
    'Could not bump the server because the invite link is invalid (expired?)' => 'لم يتم رفع السيرفر بنجاح لأن رابط الدعوة غير صالح',
    'Could not delete the server' => 'لم يتم حذف السيرفر',
    'Could not delete the review' => 'لم يتم حذف التقييم',
    'Created at {datetime}' => 'تم إنشاؤه بـ{datetime}',
    'Dashboard' => 'لوحة الإعدادات',
    'Descending' => 'تنازلي',
    'Description' => 'وصف',
    'Delete server' => 'حذف السيرفر',
    'Delete reply' => 'حذف الرد',
    'Delete review' => 'حذف التقييم',
    'DISBOARD bot API server is offline' => 'ديسبورد غير متاح حالياً',
    'DISBOARD bot must be in the server to review' => 'بوت الديسبورد يجب أن يكون في السيرفر للتقييم',
    'Discord servers partnered with <span class="brand">DISBOARD</span>' => 'سيرفرات ديسكورد مشتركة مع <span class="brand">ديسبورد</span> ',
    'Discord Server List' => 'قائمة سيرفرات الديسكورد',
    'Discord Server Reviews' => 'تقييمات السيرفرات',
    'Discord Servers Bumped Recently' => 'سيرفرات تم رفعها مؤخراً',
    'Discord servers categorized as <strong>{category}</strong>' => '<strong>{category}</strong> تصنف سيرفرات الديسكورد لـ',
    'Discord servers tagged with {tag}' => 'لسيرفرات بتاغ{tag}',
    '<span class="discord-logo">Discord</span> Servers' => '<span class="discord-logo">Discord</span> سيرفرات',
    'Discord servers tagged with <strong>{tag}</strong>' => '<strong>{tag}</strong>لسيرفرات بهاشتاغ',
    'Don\'t forget to check "Set this link to never expire"' => 'لا تنسَ جعل رابط الدعوة غير منتهي الصلاحية',
    'Edit' => 'تعديل',
    'Edit Server' => 'تعديل السيرفر',
    'Enter keyword(s)' => 'كلمات مفتاحية',
    'Failed to Sync' => 'فشل في التزامن',
    'Games' => 'ألعاب',
    'Gaming' => 'العب',
    'Get link' => 'احصل على الرابط',
    'Go to Dashboard' => 'الذهاب للوحة الإعدادات',
    'Go Back' => 'الرجوع',
    'Go Home' => 'اذهب الى القائمةالرئيسية',
    'Guidelines' => 'التعليمات',
    'Home' => 'القائمةالرئيسية',
    'If you don\'t add the bot, you can NOT present information about your server, create an invitation link or bump up your servers with commands' => 'إذا لم تقم بإضافة البوت ، فلا يمكنك تقديم معلومات حول السيرفر الخاص بك ، أو إنشاء رابط دعوة أو رفع الأوامر إلى السيرفرات الخاصة بك',
    'If your server isn\'t in the above list or dropdown, sync with Discord manually' => 'إذا لم يكن السيرفر الخاص بك في القائمة أعلاه أو القائمة المنسدلة ، فقم بالمزامنة مع ديسكورد يدويًا',
    'Invite is not set' => 'لم يتم تعيين الدعوة',
    'You can now write reviews and add ratings for servers you are joining.<br>Let\'s recommend your favorite servers to other people!' => 'يمكنك الآن كتابة تقييمات وإضافة تصنيفات للسيرفرات التي تنضم إليها.<br>دعنا نوصي السيرفرات المفضلة لديك لأشخاص آخرين!',
    'Invite Link' => 'رابط الدعوة',
    'Invalid Invite' => 'رابط غير صحيح',
    'Join <a href="{invite}">our server</a> and check the requirements on <span class="tag is-light">#partners</span> channel' => 'ادخل <a href="{invite}">سيرفرنا</a> وانظر الى المتطلبات على قناة <span class="tag is-light">#partners</span>',
    'Join this Server' => 'انضم إلى هذا السيرفر',
    'Join this server to be the first reviewer!' => 'إنضم إلى السيرفر لتكون أول مقيم!',
    'Language' => 'لغة',
    'Login' => 'تسجيل الدخول',
    'Logout' => 'تسجيل الخروج',
    'Main Language' => 'اللغة الرئيسية',
    'Member Count' => 'عدد الأعضاء',
    '<b>{number}</b> online' => '<b>{number}</b> متاح', // online member count
    '<b>{number}</b> total' => '<b>{number}</b> الكلي', // toal member count
    '{time, plural, =1{# minute} other{# minutes}}' => '{time, plural, =1{# دقيقة} other{# دقائق}}',
    'New!' => '!جديد',
    'New Review' => 'إضافة تقييم',
    'Maximum number of muted servers exceeded. To mute a server, go to Settings and unmute another server.' => 'تم تجاوز الحد الأقصى لعدد السيرفرات التي تم كتم صوتها. لكتم صوت سيرفر ، انتقل إلى "الإعدادات" وألغِ كتم صوت سيرفر آخر.',
    'More about {appName}' => '{appName} المزيد عن',
    'Mute this server' => 'كتم السيرفر',
    'Muted servers' => 'السيرفرات المكتومة',
    'Muted {serverName}' => '{serverName} صامت',
    'Not Found' => 'غير موجود',
    'No reviews and ratings yet' => 'لا يوجد تقييات',
    'No results found for <strong>{keyword}</strong>' => '<strong>{keyword}</strong> لا توجد نتائج لـ',
    'NSFW' => 'غير آمن لاستخدام الأطفال',
    'NSFW server' => 'سيرفرات غير آمنة لاستخدام الأطفال',
    'Official Discord Server' => 'سيرفر رسمي',
    'Official verified partners' => 'شركاء رسميين',
    'Owner servers' => 'سيرفرات المالك',
    'Partners' => 'شركاء',
    'Please check the checkbox below before bumping "<strong>{serverName}</strong>"' => 'الرجاء اضغط البوكس تحت قبل عمل البمب ل "<strong>{serverName}</strong>"',
    'Please check the checkbox below before joining "<strong>{serverName}</strong>"' => 'الرجاء اضغط البوكس تحت قبل دخول "<strong>{serverName}</strong>"',
    'Please enter no more than {tagLimit} tags.' => 'الرجاء لا تضع اكثر من {tagLimit} شعارات',
    'Please select a server' => 'الرجاء اختيار سيرفر',
    'Please wait another {0, plural, =1{# minute} other{# minutes}} until the server can be bumped' => 'الرجاء انتظر {0, plural, =1{# ديقيقة} other{# دقائق}} حتى يمكن ان يعمل للسيرفر بمب',
    'Please wait another {0, plural, =1{# minute} other{# minutes}} until you can bump' => 'الرجاء انتظر {0, plural, =1{# ديقيقة} other{# دقائق}} حتى يمكنك انت ان تقوم بالبمب',
    'Popular Tags' => 'تاغات مشهورة',
    'Private' => 'خاص',
    'Public' => 'عام',
    'Public Discord Servers' => 'سيفرات عامة',
    'Public Discord Server List' => 'قائمة السيرفرات العامة',
    'Rating' => 'التقييم',
    'Ratings & Reviews' => 'التقييمات',
    'Read more' => 'اعرف المزيد',
    'reCAPTCHA failed' => 'reCAPTCHAفشل في الـ',
    'Recommended' => 'موصى به',
    'Redirecting' => 'إعادة توجيه',
    'Reply' => 'كتابة رد',
    'Reply to Review' => 'الرد على التقييم',
    'Report Description' => 'وصف البلاغ',
    'Report Server' => 'أبلغ عن السيرفر',
    'Report this server' => 'أبلغ عن هذا السيرفر',
    'Report Type' => 'نوع البلاغ',
    'Review' => 'تقييم',
    'Review should be personal feedback only. <br>Do not harm someone\'s reputation, whether it is fact or not.' => 'التقييم يجب ان يكون ملاحظات شخصية فقط.<br> لا تضرر سمعة شخص اخر, حتى لو كان حقيقة ام لا.',
    'Reviews' => 'التقييمات',
    'Reviewed by' => 'تم كتابة التقييم  من واسطة',
    '{count, plural, =1{<b>#</b> review} other{<b>#</b> reviews}}' => '{count, plural, =1{<b>#</b> تقييم} other{<b>#</b> تقييمات}}',
    'Review {serverName}' => '「{serverName}」تقييم',
    'Reviews of {serverName}' => 'تقييمات عن {serverName}',
    'Save' => 'حفظ',
    'See: <a href="{url}" target="_blank">screen capture</a>' => 'أنظر: <a href="{url}" target="_blank">تصوير الشاشة</a>',
    'Search' => 'بحث',
    'Search Discord Servers' => 'ابحث عن سيرفرات ديسكورد',
    'Search Options' => 'خيارات البحث',
    'Search results for: {keyword}' => '{keyword} ابحث عن نتائج لـ',
    'Select a Category' => 'اختر فئة',
    'Select Language' => 'اختر لغة',
    'Select a Server' => 'اختر سيرفر',
    'Select a server to add to the public server list on DISBOARD' => 'اختر سيرفر لإضافته لقائمة السيرفرات العامة',
    'Select a server to review' => 'اختر سيرفر للتقييم',
    'Send the invite command: `!d invite #channel`' => 'إرسل امر: `d invite #channel!`',
    'Separate by <b>space</b>' => 'اافصل ب <b>space</b>',
    'Settings' => 'الإعدادات',
    'Servers' => 'سيرفرات',
    'Server admin?' => 'أدمن السيرفر؟',
    '{num, plural, =1{# shard is dead} other{# shards are dead}}' => '{num, plural, =1{الشارد # لا يعمل} other{# شارد لا تعمل}}',
    'Showing <b>{from}</b> - <b>{to}</b> of <strong>{total} servers</strong>' => 'يتم عرض <b>{from}</b> - <b>{to}</b> من <strong>{total} سيرفرات</strong>',
    'Showing <b>{from}</b> - <b>{to}</b> of <strong>{total} reviews</strong>' => 'يتم عرض <b>{from}</b> - <b>{to}</b> من <strong>{total} تقييمات</strong>',
    'Sort by' => 'مرتبة بحسب',
    'Submit' => 'إرسال',
    'Support' => 'الدعم',
    'Sync servers' => 'تزامن السيرفرات',
    'Synced with Discord' => 'متزامن مع ديسكورد',
    'Tags' => 'تاغات',
    'Tags similar to {tag}' => 'شعارات تشبه {tag}',
    'Terms of Service' => 'شروط الاستخدام',
    'The invite of this server is invalid or has expired.' => 'الدعاء لهذا السيرفر غير صالح او منتهي الصلاحية',
    'The report has been sent' => 'تم ارسال البلاغ',
    'The server is set to private' => 'هذا السيرفر خاص',
	'This server has been removed due to breaking our guidelines' => 'تم ازالة هذا السيرفر بسبب كسره للقواعد الاشارية',
    'This server is private. Only the owner (you) can view it.' => 'هذا السيرفر خاص فقط المالك (انت) يمكنه رؤيته',
    'This site is protected by reCAPTCHA and the Google <a href="https://policies.google.com/privacy">Privacy Policy</a> and <a href="https://policies.google.com/terms">Terms of Service</a> apply.' => 'هذه الصفحة محمية بالكابتشا و <a href="https://policies.google.com/privacy">سياسة جوجل الخاصة> و <a href="https://policies.google.com/terms">شروط الخدمة</a> تطبق. ',
    'This review has been removed due to breaking our guidelines' => 'تم ازالة هذا التقييم بسبب كسره للقواعد الارشادية',
	'This will add this server to our public server list' => 'هذا سيضيف هذا السيرفر الى قائمة السيرفرات العامة لدينا',
    'Title' => 'لقب',
    '{tag1} and {tag2}(nsfw) tags cannot be set together' => '{tag1} و {tag2} (غير امنة للعمل) لا يمكن ان تضع مع بعض',
    '<b>{total}</b> servers in total' => 'مجموع السيرفرات <b>{total}</b> ',
    '<b>{total}</b> reviews in total' => 'مجموع التقييمات <b>{total}</b>',
    'Unmute' => 'ازالة الكتم',
    'Unmuted {serverName}' => '{serverName} غير مكتوم',
    'Unspecified' => 'غير محدد',
    'Up to {limit} tags' => 'حتى {limit} اشعار',
    'User' => 'مستخدم',
    'Users' => 'مستخدمين',
    'View' => 'عرض', // view server button on Dashboard
    'Want to be a partner?' => 'تريد ان تكون شريك؟',
    'Why don\'t you review your favorite <span class="discord-logo">Discord</span> server?' => 'لماذا لا تقيم السيرفر <span class="discord-logo">Discord</span> المفضل لك؟',
    'Why don\'t you <a href="{reviewUrl}">review <strong>{serverName}</strong></a>?' => 'لماذاا لا <a href="{reviewUrl}">تقيم <strong>{serverName}</strong></a>؟',
    'You have already muted {serverName}' => 'لقد كتمت {serverName} من قبل',
    'You haven\'t added a server yet' => 'لم تضف سيرفر قط',
    'You must be logged in to mute a server' => 'يجب تسجيل الدخول لكتم السيرفر ',
    'You must be a member of the server to review it' => 'يجب ان تكون في السيرفر لتعطي تقييمك',
    'You need to be in the server for at least {duration} days to review' => 'يجب ان تكون في السيرفر على الاقل {duration} ايام لتعطي تقييمك',
    'You need to follow our <a href="{url}" target="_blank">Guidelines</a>' => 'يجب ان تتبع <a href="{url}" target="_blank">قواعدنا الارشادية</a>',
    'You seem like a robot' => 'تبدو مثل الروبوت',
    'Your servers' => 'سيرفراتك',
    'Your reviews' => 'تقييماتك',
    'Your server has been bumped' => 'تم رفع سيرفرك',
    'Your server has been deleted' => 'تم حذف سيرفرك',
    'Your server has been saved successfully' => 'تم حفظ سيرفرك بنجاح',
    'Your reply has been deleted' => 'تم حذف الرد',
    'Your reply has been saved successfully' => 'تم حفظ ردك بنجاح',
    'Your review has been deleted' => 'تم حذف تقييمك',
    'Your review has been saved successfully' => 'تم حفظ التقييم بنجاح',
    'just now' => 'في هذة اللحظة',
    '{0, plural, =1{# day} other{# days}} ago' => '{0, plural, =1{# يوم} other{# أيام}} قبل',
    '{0, plural, =1{# hour} other{# hours}} ago' => '{0, plural, =1{# ساعة} other{# ساعات}} قبل',
    '{0, plural, =1{# minute} other{# minutes}} ago' => '{0, plural, =1{# دقيقة} other{# دقائق}} قبل',
    '{0, plural, =1{# second} other{# seconds}} ago' => '{0, plural, =1{# ثانية} other{# ثواني}} قبل',
    'DISBOARD was made to make everyone enjoy Discord more.<br>We hope you find awesome Discord servers and friends here 😊.' => 'ديسبورد عمل ليجعل الجميع يستمتع بديسكورد اكثر.<br>نأمل ان تجد سيرفرات واصدقاء رائعة 😊.',
    /* Rules, ToS */
    'Name or description contains insult or swear words' => 'الاسم او الوصف فيه اهانات',
    'Spam / fake server' => 'سيرفر غير حقيقي',
    'Invite is invalid or expired' => 'الدعو غير صالح او منتهي الصلاحية',
    /* Welcome Messages on home page */
    'Discover <span class="discord-logo">Discord</span> Servers' => 'اكتشف سيرفرات <span class="discord-logo">ديسكورد</span>',
    'We connect <strong>Discord servers</strong> and <b>people</b> together' => 'نحن نصل <strong>سيرفرات الدسيكورد</strong> و <b>الناس</b> مع بعض',
    '<strong class="brand">DISBOARD</strong> is the place where you can <strong>list/find Discord servers</strong>.' => '<strong class="brand">ديسبورد</strong> هو المكان الذي يمكنك <strong>تجد و تنزل سيرفرات ديسكورد ',
    'Find and join some awesome servers listed here.' => 'جد و ادخل سيرفرات رائعة موجودة هنا',
    'Or <a href="{login-url}">login</a> and <strong>add your server if you are a server owner</strong> 😎' => 'او <a href="{login-url}">سجل الدخول</a> و <strong>ضف سيرفرك اذا انت تملكه</strong> 😎',
    'Add Your Server!' => 'أضف سيرفرك', // The large button
    /* Categories */
    'Adventure Games' => 'ألعاب مغامرات',
    'All Games' => 'كل الألعاب',
    'Anime · Manga' => 'مانجا・أنيمي',
    'Community' => 'مجتمع',
    'Computers' => 'كمبيوترات',
    'FPS Games' => 'FPSألعاب',
    'MMO Games' => 'MMOألعاب',
    'MOBA Games' => 'MOBAألعاب',
    'Movies' => 'أفلام',
    'Music' => 'موسيقى',
    'Other' => 'آخر',
    'Party Games' => 'ألعاب حفلات',
    'Programming' => 'برمجة',
    'Puzzle Games' => 'ألعاب الألغاز',
    'RPG Games' => 'RPG',
    'Retro Games' => 'ألعاب كلاسيكية',
    'Sandbox Games' => 'العاب التجربة',
    'Simulation Games' => 'ألعاب المحاكاة',
    'Sports Games' => 'ألعاب رياضية',
    'Strategy Games' => 'ألعاب استراتيجية',
    'Technology' => 'تكنولوجيا',
    'TCG Games' => 'TCG',
    'Tabletop Games' => 'ألعاب الطاولة',
    'Fighting Games' => 'ألعاب قتال',
    /* Meta Descriptions */
    'DISBOARD is the public Discord server listing community. You can search Discord servers by your interest like Gaming, Anime, Music, etc. Find and join some awesome servers listed here!' => 'ديسبورد هو قائمة سيرفرات ديسكورد العامة. يمكنك ان تبحث سيرفرات الديسكورد حسب اهتمماتك مثل الجيمنج و الانيمي وغيرها. جد و ادخل سيرفرات رائعة هنا!',
    'Search results for: {keyword}. There {count, plural, =1{is # server which is} other{are # servers which are}} waiting for your joining!' => 'نتائج البحث ل: {keyword}. هناك {count, plural, =1{# سيرفر الذي هو} other{# سيرفرات التي هي}} ',
    'List of Discord servers tagged with {tag}. Find and join some awesome servers listed here!' => 'قائمة سيرفرات بشعار {tag}. جد وادخل سيرفرات رائعة موجودة هنا!',
];
